# Generated by Django 5.1.7 on 2025-04-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_instructor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_student',
        ),
        migrations.AddField(
            model_name='profile',
            name='personality',
            field=models.CharField(choices=[('instructor', 'is_instructor'), ('student', 'is_student')], default='is_student', max_length=20),
        ),
    ]
